# Generated by Django 4.2.4 on 2023-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100, null=True)),
                ('vehicle_type', models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Three Wheeler', 'Three Wheeler'), ('Four Wheeler', 'Four Wheeler')], max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_description', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
